######################## default configuration ####################
baseURL = "https://innersourcecommons.org"
title = "InnerSource Gathering Tokyo 2024"
themesDir = "../themes"
theme = "gathering-theme"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
    defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/syotimer/syotimer.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Speakers"
  URL = "speaker"
  weight = 3

  [[menu.main]]
  weight = 4
  name = "Pages"
  hasChildren = true

    [[menu.main]]
    parent = "Pages"
    name = "Tickets"
    URL = "pricing"

    [[menu.main]]
    parent = "Pages"
    name = "Blog"
    URL = "blog"

    [[menu.main]]
    parent = "Pages"
    name = "Schedule"
    URL = "schedule"

    [[menu.main]]
    parent = "Pages"
    name = "FAQ"
    URL = "faq"
    
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5

#################### default parameters ################################
[params]
logo = "images/gathering-tokyo-2024.png"
home = "Home"
# Meta data
description = "InnerSource Gathering Tokyo 2024"
author = "InnerSource Gathering Organizors"
# email address
email = "gathering@innersource.org"
# contact form action
contact_form_action = "" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# search for blog page
search = true

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Register"
link = "https://innersourcecommons.org"


# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=0363fb06e6a59d48c6e260f1b&amp;id=97224b5ff2"
mailchimp_form_name = "b_0363fb06e6a59d48c6e260f1b_97224b5ff2"

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "35.6678347"
map_longitude = "139.7500377,15"
map_marker = "images/marker.png"


############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/InnerSourceJP"

[[params.social]]
icon = "tf-ion-social-linkedin"
link = "https://www.linkedin.com/company/innersourcecommons/"

[[params.social]]
icon = "tf-ion-social-youtube"
link = "https://www.youtube.com/@InnerSourceCommonsJapan"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/en"
weight = 1
home = "Home"
# footer content
footer_content = """
InnerSource Commons は、InnerSource のグローバルコミュニティです。
2015年に設立され、現在では750以上の企業、学術機関、政府機関から3000人以上の個人をサポートし、つなぎ合わせています。
InnerSource の始め方やベストプラクティスを共有し、InnerSource の価値観や原則についての議論を促進しています。
"""
# copyright
copyright = """
[行動規範](https://innersourcecommons.org/ja/about/codeofconduct/)<br>
Copyright &copy; 2024
"""
